name: date_rule
description: Parses Apility Date Rules

version: 1.0.1
repository: https://github.com/apility/rule-builder-dart
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  uuid: any

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
